### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by Christianalamassi** [Christianalamassi/E-commerce#1]
As a **User**, I can **register an account**, so that **I can access benefits of the project**.

**Acceptance criteria**

 

- [x] User can create an account
- [x]  Then Log in then.
- [x]  access the user profile.
- [x]  then buy products
- [x]  receive a confirmation email

**Tasks**

- [x]  Download Allauth
