### ISSUE TITLE
Payment mathed

### ISSUE THREAD

**Issue by Christianalamassi** [Christianalamassi/E-commerce#12]
As a **User** I can **order and pay** so that **I do complete buying processes**

**-Acceptance criteria** 

- [x] A user can select the Drinks
- [x] than go to payment page
- [x] than does the payment 

**Tasks**

- [x] Download  strip
- [x] bulled a model payment 

-
